title: Juan Antonio Castro # your name (or website title) here
logo: "/images/JuanCastro_Pic1.0.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  This is my portfolio 
  <br><br>
  <a href="https://www.linkedin.com/in/juan-antonio-castro-price/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
